steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/projectdicodingasik/my-portfolio-us', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/projectdicodingasik/my-portfolio-us']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-portfolio-us'
      - '--image'
      - 'gcr.io/projectdicodingasik/my-portfolio-us'
      - '--region'
      - 'us-west1'
